Repository matomo-org/matomo-for-wordpress, pull requests merged in 2020-02, with the labels that each got.

#199 Fix wp-external-links incompatibility
  app/bootstrap.php
Labels: not-in-changelog

#205 Fix cart updates were not tracked
  classes/WpMatomo/Ecommerce/EasyDigitalDownloads.php
  classes/WpMatomo/Ecommerce/MemberPress.php
  classes/WpMatomo/Ecommerce/Woocommerce.php
Labels: not-in-changelog

#216 Ensure we have a time set for visit last action time
  app/core/Tracker/GoalManager.php
Labels: needs patching after core release, not-in-changelog

#217 When doing ajax, do not execute cart update event twice in WooCommerce
  classes/WpMatomo/Ecommerce/Base.php
  classes/WpMatomo/Ecommerce/Woocommerce.php
Labels: not-in-changelog

#218 mention 7.2 requirement in description text
  readme.txt
Labels: c: Documentation

#219 fix two minor typos
  readme.txt
Labels: c: Documentation

#220 losslessly compress plugin page images
  .wordpress-org/banner-1544x500-rtl.png
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250-rtl.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-10.png
  .wordpress-org/screenshot-11.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
  .wordpress-org/screenshot-9.png
Labels: not-in-changelog

#229 Add possibility to configure login url
  classes/WpMatomo/Admin/views/access.php
  plugins/WordPress/Controller.php
  plugins/WordPress/WordPress.php
Labels: not-in-changelog

#231 Allow configuration of MaxMind GeoIP DB
  classes/WpMatomo/Admin/AdminSettings.php
  classes/WpMatomo/Admin/GeolocationSettings.php
  classes/WpMatomo/Admin/views/exclusion_settings.php
  classes/WpMatomo/Admin/views/geolocation_settings.php
  classes/WpMatomo/ScheduledTasks.php
  classes/WpMatomo/Settings.php
Labels: not-in-changelog
