Repository matomo-org/matomo-for-wordpress, pull requests merged in 2021-09, with the labels that each got.

#509 Only register scheduled tasks if Matomo looks like it is installed
  classes/WpMatomo/ScheduledTasks.php
Labels: Needs Review

#511 Matomo opt out as a gutenberg block
  assets/js/blocks/matomo_opt_out.js
  classes/WpMatomo/Admin/views/get_started.php
  classes/WpMatomo/Admin/views/privacy_gdpr.php
  classes/WpMatomo/OptOut.php
Labels: Needs Review

#504 Restore the default date management
  classes/WpMatomo/Admin/Summary.php
  plugins/WordPress/Menu.php
  plugins/WordPress/WordPress.php
  plugins/WordPress/stylesheets/user.css
Labels: Needs Review

#516 add post-smtp as incompatible plugin
  classes/WpMatomo/Admin/Summary.php
  classes/WpMatomo/Admin/SystemReport.php
  classes/WpMatomo/OptOut.php
  classes/WpMatomo/ScheduledTasks.php
Labels: compatibility with other plugins

#518 avoid execution if wp_get_order return false
  classes/WpMatomo/Ecommerce/Woocommerce.php
Labels: Bug, Needs Review

#521 enable the rest_route via $_GET parameter
  classes/WpMatomo/API.php
Labels: Bug

#522 When archiving is forced, print full error message
  classes/WpMatomo/ScheduledTasks.php
Labels: Needs Review
